# Generated by Django 3.0.8 on 2021-12-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidavariacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_line_1', models.CharField(max_length=150)),
                ('direccion_line_2', models.CharField(max_length=150)),
                ('cuidad', models.CharField(max_length=150)),
                ('addres_type', models.CharField(choices=[('B', 'Facturacion'), ('S', 'Envio')], max_length=1)),
                ('defecto', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incio_fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_fecha', models.DateTimeField(blank=True, null=True)),
                ('ordenn', models.BooleanField(default=False)),
                ('envio_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envio_direccion', to='cart.Direccion')),
                ('facturacion_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturacion_direccion', to='cart.Direccion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('descripcion', models.TextField()),
                ('precio', models.PositiveIntegerField(default=1)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activado', models.BooleanField(default=False)),
                ('avalible_bebida', models.ManyToManyField(to='cart.Bebidavariacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Paypal', 'Paypal')], max_length=20)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('sucecesful', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('raw_repuesta', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.Orden')),
            ],
        ),
        migrations.CreateModel(
            name='ordenIten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Bebidavariacion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Producto')),
            ],
        ),
    ]
